PP-389: New material theme
ThePalaceProject/android-core pull request #241
Opened 2023-10-16 16:42 UTC by io7m

**What's this do?**
This makes all of the various changes to use the new Palace material theme. The old Simplified theme code and neutral theme are completely removed.

**Why are we doing this? (w/ JIRA link if applicable)**
https://ebce-lyrasis.atlassian.net/browse/PP-389

**How should this be tested? / Do these changes have associated tests?**
This is a tough one because the changes are all visual. Problems are likely to be of the type "I can't see a UI element that I'm supposed to be see" or "Something is misaligned".

**Dependencies for merging? Releasing to production?**
None really, but this will need a lot of informal testing. I'd rather it went out in 1.7.0 than 1.6.1.

**Have you updated the changelog?**
Not yet, because we've yet to push 1.6.1, and this will probably be 1.7.0.

**Has the application documentation been updated for these changes?**
N/A

**Did someone actually run this code to verify it works?**
@io7m Ran the app and the various viewers a lot.

2023-10-16 17:23 UTC, io7m commented
The build is failing because we need to deploy snapshots of the audiobooks and r2 components to Central. We'll need to coordinate this, because we don't want those changes going out in 1.6.1...

2023-10-17 10:56 UTC, io7m commented
I've just realized I missed out the tabbed button changes. I'll add these today.

2023-10-17 16:23 UTC, nunommts requested changes
This looks really good! I have just one small comment on the PlayerTimer argument change

2023-10-17 16:23 UTC, nunommts commented on simplified-viewer-audiobook/src/main/java/org/librarysimplified/viewer/audiobook/AudioBookPlayerActivity.kt
> +      val fragment = PlayerSleepTimerFragment.newInstance(PlayerFragmentParameters())
This shouldn't be here because when the audiobook submodule versions are correctly implemented and imported, we'll have an error

2023-10-17 16:29 UTC, io7m commented
Done.

2023-10-23 11:56 UTC, merged