Updated libraries version
ThePalaceProject/android-core pull request #255
Opened 2023-11-08 17:40 UTC by nunommts

**What's this do?**
Updated the libraries version so we can have the latest changes on the Palace HTTP submodule

**Why are we doing this? (w/ JIRA link if applicable)**
There's a [comment](https://ebce-lyrasis.atlassian.net/browse/PP-602?focusedCommentId=12532) saying the SAML download bug is still happening

**How should this be tested? / Do these changes have associated tests?**
Follow the steps of [this card](https://ebce-lyrasis.atlassian.net/browse/PP-602).

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

2023-11-09 13:57 UTC, io7m commented
Is this actually still relevant? The platform has been updated multiple times since this was submitted.

2023-11-09 16:08 UTC, nunommts commented
@io7m hmm, you're right. If there's a more recent version of the platform then this is not needed. However, I'll use and adapt this for my next PR :D

2023-11-09 17:48 UTC, nunommts commented
@io7m it's ready for review 😄

2023-11-10 12:31 UTC, io7m commented on simplified-notifications/src/main/java/NotificationTokenHTTPCalls.kt
> +                logger.error(
I don't think this should be at `error` severity. It'll cause a non-fatal event to be logged to Crashlytics. This is probably just `debug`.

2023-11-10 12:33 UTC, io7m requested changes
Seems good, just one small adjustment needed.

2023-11-10 14:03 UTC, io7m approved these changes
:rocket:

2023-11-10 14:06 UTC, merged